services:
  tokenizer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tokenizer_app
    environment:
      - DB_HOST=<remote-db-host>
      - DB_PORT=80
      - DB_USER=fintreck_user
      - DB_PASSWORD=your_password
      - DB_NAME=fintreck_db
      - DB_SSLMODE=disable
    ports:
      - "7777:7777"
    restart: unless-stopped
